# Etapa 1: build com Maven
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Etapa 2: imagem final para execução
FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Porta usada pelo Spring Boot (ajuste se necessário)
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
