version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-verificacontato
    environment:
      MYSQL_DATABASE: verificacontato
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - verificanet

  app:
    build: .
    container_name: verificacontato-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/verificacontato
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - verificanet

volumes:
  mysql-data:

networks:
  verificanet:

